### ISSUE TITLE
Can't find a suitable X11 include directory

### ISSUE THREAD

**Issue by shkipan** [ttshivhula/minilibx#2]
Good day!
I've tried to install mlx into Ubuntu console on Windows. But after executing "make" command i've got this message about X11. 
I've already performed sudo apt install libx11-dev but nothing helped.
Can you give me a hint what to do?

**Comment by ttshivhula** [comment]
Can you please dump the error message here so that i will be able to assist

**Comment by shkipan** [comment]
This one

![image](https://user-images.githubusercontent.com/33808396/55613273-02c84880-5793-11e9-86f3-47f140b13386.png)

**Comment by shkipan** [comment]
Sorry, any updates?

**Comment by ttshivhula** [comment]
No I'm on Arch Linux and I am not getting that error everything compiles just fine... I will install Ubuntu on computer and try to install the lib and then fix the error if I get it

**Comment by ttshivhula** [comment]
Dude you can't install on Ubuntu for windows since it doesn't support graphical apps on command line apps. Download Ubuntu and try it should work

**Comment by Sulfiore** [comment]
@ttshivhula Yes it does, I installed xserv on Windows
Now I can run fdf binaries from my Ubuntu shell onto my Windows.
1: https://wiki.ubuntu.com/WSL#Running_Graphical_Applications
2: ![image_2020-04-20_21-11-31](https://user-images.githubusercontent.com/3856645/79790262-c6d73580-834b-11ea-816e-57c602c3ef2a.png)

But when compiling, it doesn't work and I have the same error as @shkipan

**Comment by Sulfiore** [comment]
I found the problem, you need to install `libxext-dev`
and then you need to modify the configure file, and add `/usr/include              \ `

because it doesn't search in the right path

**Comment by michaelgiraldo** [comment]
another package to install libbsd-dev
